<?php

$pconfig = array(
	'title'   => '区域关卡',
	'table'   => 'mission_level',
	'links'   => array(),
	'columns' => array(
		array('name' => 'name', 'text' => '关卡名称', 'width' => '150'),
		array('name' => 'lock', 'text' => '开启权值', 'width' => '80'),
		array('name' => 'award_lock', 'text' => '通关奖励权值', 'width' => '80'),
		array('name' => 'type', 'text' => '关卡类型', 'width' => '90px',),
		array('name' => 'sign', 'text' => '场景资源标识', 'width' => '120'),
		array('name' => 'sign_war', 'text' => '战斗资源标识', 'width' => '120'),
		array('name' => 'flip_horizontal', 'text' => '水平翻转', 'width' => '50'),
		array('name' => 'music', 'text' => '音乐资源标识', 'width' => '150'),
		array('name' => 'enter_x', 'text' => '出生点x', 'width' => '50'),
		array('name' => 'enter_y', 'text' => '出生点y', 'width' => '50'),
		array('name' => 'daily_num', 'text' => '每天进入次数(-1不限)', 'width' => '50'),
		array('name' => 'physical', 'text' => '每次进入消耗体力', 'width' => '50'),
		array('name' => 'box_x', 'text' => '宝箱x', 'width' => '50'),
		array('name' => 'box_y', 'text' => '宝箱y', 'width' => '50'),
		array('name' => 'box_dir', 'text' => '宝箱朝向', 'width' => '50'),
		array('name' => 'award_type', 'text' => '奖励类型', 'width' => '50'),
		array('name' => 'award_item', 'text' => '奖励物品', 'width' => '50'),
		array('name' => 'award_item_num', 'text' => '奖励物品数量', 'width' => '50'),
		array('name' => 'award_key', 'text' => '奖励钥匙数', 'width' => '50'),
		array('name' => 'award_exp', 'text' => '奖励经验', 'width' => '50'),
		array('name' => 'award_coin', 'text' => '奖励铜钱', 'width' => '50'),
		array('name' => 'award_relationship', 'text' => '奖励友情', 'width' => '50'),
		array('name' => 'award_box', 'text' => '奖励宝箱', 'width' => '50', 'default' => '1'),
		array('name' => 'award_pet', 'text' => '出现灵宠', 'width' => '50'),
	),
	'opera' => array(
		array('type' => 'link', 'text' => '地图怪物', 'render' => 'map_enemy_render'),
	),
	'insert' => 'sql_insert',
	'where' => 'sql_where',
	'location' => 'location',
	'js'=>'js_function',
);
?>
