package mdb

func (file *SyncFile) initRPCTransInfo() error {
	file.BeginTrans()
	file.WriteBytes([]byte("65541,TRANS_TAG_RPC_Call_AddRecord,65542,TRANS_TAG_RPC_Serve_AddRecord,65543,TRANS_TAG_RPC_Call_GetFriendsWithMultiLevel,65544,TRANS_TAG_RPC_Serve_GetFriendsWithMultiLevel,65545,TRANS_TAG_RPC_Call_CreateAnnouncement,65546,TRANS_TAG_RPC_Serve_CreateAnnouncement,65547,TRANS_TAG_RPC_Call_EnterArena,65548,TRANS_TAG_RPC_Serve_EnterArena,65549,TRANS_TAG_RPC_Call_SwapPlayerRank,65550,TRANS_TAG_RPC_Serve_SwapPlayerRank,65551,TRANS_TAG_RPC_Call_MailSend,65552,TRANS_TAG_RPC_Serve_MailSend,65553,TRANS_TAG_RPC_Call_InviteFriendWithMultiLevel,65554,TRANS_TAG_RPC_Serve_InviteFriendWithMultiLevel,65555,TRANS_TAG_RPC_Call_AwardMultiLevel,65556,TRANS_TAG_RPC_Serve_AwardMultiLevel,65557,TRANS_TAG_RPC_Call_GetPlayerMultiLevelInfo,65558,TRANS_TAG_RPC_Serve_GetPlayerMultiLevelInfo,65559,TRANS_TAG_RPC_Call_SetPlayerInfo,65560,TRANS_TAG_RPC_Serve_SetPlayerInfo,65561,TRANS_TAG_RPC_Call_GetPlayerInfo,65562,TRANS_TAG_RPC_Serve_GetPlayerInfo,65563,TRANS_TAG_RPC_Call_GetPlayerInfoWithOpenId,65564,TRANS_TAG_RPC_Serve_GetPlayerInfoWithOpenId,65565,TRANS_TAG_RPC_Call_GetTargetPlayerRank,65566,TRANS_TAG_RPC_Serve_GetTargetPlayerRank,65567,TRANS_TAG_RPC_Call_NewPlayerFighter,65568,TRANS_TAG_RPC_Serve_NewPlayerFighter,65569,TRANS_TAG_RPC_Call_AwardArenaBox,65570,TRANS_TAG_RPC_Serve_AwardArenaBox,65571,TRANS_TAG_RPC_Call_GetTargetFighterForDrivingSwordVisting,65572,TRANS_TAG_RPC_Serve_GetTargetFighterForDrivingSwordVisting,65574,TRANS_TAG_RPC_Call_IdipBanUser,65575,TRANS_TAG_RPC_Serve_IdipBanUser,65576,TRANS_TAG_RPC_Call_IdipUnBanUser,65577,TRANS_TAG_RPC_Serve_IdipUnBanUser,65578,TRANS_TAG_RPC_Call_IdipGetUserInfo,65579,TRANS_TAG_RPC_Serve_IdipGetUserInfo,65580,TRANS_TAG_RPC_Call_IdipGetEquipInfo,65581,TRANS_TAG_RPC_Serve_IdipGetEquipInfo,65582,TRANS_TAG_RPC_Call_IdipGetBagInfo,65583,TRANS_TAG_RPC_Serve_IdipGetBagInfo,65584,TRANS_TAG_RPC_Call_IdipGetSoulInfo,65585,TRANS_TAG_RPC_Serve_IdipGetSoulInfo,65586,TRANS_TAG_RPC_Call_IdipSendItem,65587,TRANS_TAG_RPC_Serve_IdipSendItem,65588,TRANS_TAG_RPC_Call_IdipDelItem,65589,TRANS_TAG_RPC_Serve_IdipDelItem,65590,TRANS_TAG_RPC_Call_IdipUpdateMoney,65591,TRANS_TAG_RPC_Serve_IdipUpdateMoney,65592,TRANS_TAG_RPC_Call_IdipUpdateExp,65593,TRANS_TAG_RPC_Serve_IdipUpdateExp,65594,TRANS_TAG_RPC_Call_IdipUpdatePhysical,65595,TRANS_TAG_RPC_Serve_IdipUpdatePhysical,65596,TRANS_TAG_RPC_Call_IdipUpdateHeart,65597,TRANS_TAG_RPC_Serve_IdipUpdateHeart,65598,TRANS_TAG_RPC_Call_SendHeartToPlatformFriend,65599,TRANS_TAG_RPC_Serve_SendHeartToPlatformFriend,65600,TRANS_TAG_RPC_Call_SendHeartToGameFriend,65601,TRANS_TAG_RPC_Serve_SendHeartToGameFriend,65602,TRANS_TAG_RPC_Call_SendHeartToAllGameFriends,65603,TRANS_TAG_RPC_Serve_SendHeartToAllGameFriends,65604,TRANS_TAG_RPC_Call_GetOnlineNumber,65605,TRANS_TAG_RPC_Serve_GetOnlineNumber,65608,TRANS_TAG_RPC_Call_MailBatchSend,65609,TRANS_TAG_RPC_Serve_MailBatchSend,65610,TRANS_TAG_RPC_Call_IdipGetSwordInfo,65611,TRANS_TAG_RPC_Serve_IdipGetSwordInfo,65612,TRANS_TAG_RPC_Call_IdipGetPetInfo,65613,TRANS_TAG_RPC_Serve_IdipGetPetInfo,65614,TRANS_TAG_RPC_Call_IdipUpdateGameLamp,65615,TRANS_TAG_RPC_Serve_IdipUpdateGameLamp,65616,TRANS_TAG_RPC_Call_IdipSendMail,65617,TRANS_TAG_RPC_Serve_IdipSendMail,65619,TRANS_TAG_RPC_Call_DeleteItem,65620,TRANS_TAG_RPC_Serve_DeleteItem,65621,TRANS_TAG_RPC_Call_RefuseMultiLevelRoomInvite,65622,TRANS_TAG_RPC_Serve_RefuseMultiLevelRoomInvite,65623,TRANS_TAG_RPC_Call_StartMultiLevel,65624,TRANS_TAG_RPC_Serve_StartMultiLevel,65625,TRANS_TAG_RPC_Call_MultiLevelChangeBuddy,65626,TRANS_TAG_RPC_Serve_MultiLevelChangeBuddy,65627,TRANS_TAG_RPC_Call_MultiLevelChangeForm,65628,TRANS_TAG_RPC_Serve_MultiLevelChangeForm,65630,TRANS_TAG_RPC_Call_IdipAqBanUser,65631,TRANS_TAG_RPC_Serve_IdipAqBanUser,65632,TRANS_TAG_RPC_Call_IdipAqRelievePunish,65633,TRANS_TAG_RPC_Serve_IdipAqRelievePunish,65634,TRANS_TAG_RPC_Call_IdipAqSendMail,65635,TRANS_TAG_RPC_Serve_IdipAqSendMail,65636,TRANS_TAG_RPC_Call_IdipGetRankInfoGs,65637,TRANS_TAG_RPC_Serve_IdipGetRankInfoGs,65638,TRANS_TAG_RPC_Call_IdipGetRankInfoHd,65639,TRANS_TAG_RPC_Serve_IdipGetRankInfoHd,65640,TRANS_TAG_RPC_Call_IdipCleanData,65641,TRANS_TAG_RPC_Serve_IdipCleanData,65642,TRANS_TAG_RPC_Call_IdipSetSoulLevel,65643,TRANS_TAG_RPC_Serve_IdipSetSoulLevel,65644,TRANS_TAG_RPC_Call_IdipSetSwordLevel,65645,TRANS_TAG_RPC_Serve_IdipSetSwordLevel,65646,TRANS_TAG_RPC_Call_IdipAddPet,65647,TRANS_TAG_RPC_Serve_IdipAddPet,65648,TRANS_TAG_RPC_Call_GetArenaRank,65649,TRANS_TAG_RPC_Serve_GetArenaRank,65650,TRANS_TAG_RPC_Call_IdipSendAllMail,65651,TRANS_TAG_RPC_Serve_IdipSendAllMail,65652,TRANS_TAG_RPC_Call_IdipGameLampInfo,65653,TRANS_TAG_RPC_Serve_IdipGameLampInfo,65654,TRANS_TAG_RPC_Call_IdipDelNotice,65655,TRANS_TAG_RPC_Serve_IdipDelNotice,65656,TRANS_TAG_RPC_Call_TssUserLogin,65657,TRANS_TAG_RPC_Serve_TssUserLogin,65658,TRANS_TAG_RPC_Call_TssUserLogout,65659,TRANS_TAG_RPC_Serve_TssUserLogout,65660,TRANS_TAG_RPC_Call_TssRecvData,65661,TRANS_TAG_RPC_Serve_TssRecvData,65662,TRANS_TAG_RPC_Call_TssSendData,65663,TRANS_TAG_RPC_Serve_TssSendData,65664,TRANS_TAG_RPC_Call_GetGlobalVipCount,65665,TRANS_TAG_RPC_Serve_GetGlobalVipCount,65666,TRANS_TAG_RPC_Call_GetGlobalLevelVipCount,65667,TRANS_TAG_RPC_Serve_GetGlobalLevelVipCount,65668,TRANS_TAG_RPC_Call_OperateGroupBuyCount,65669,TRANS_TAG_RPC_Serve_OperateGroupBuyCount,65671,TRANS_TAG_RPC_Call_DecMoney,65672,TRANS_TAG_RPC_Serve_DecMoney,65673,TRANS_TAG_RPC_Call_IncMoney,65674,TRANS_TAG_RPC_Serve_IncMoney,65675,TRANS_TAG_RPC_Call_IdipGetUserFight,65676,TRANS_TAG_RPC_Serve_IdipGetUserFight,65677,TRANS_TAG_RPC_Call_IdipGetHardLevelStatus,65678,TRANS_TAG_RPC_Serve_IdipGetHardLevelStatus,65679,TRANS_TAG_RPC_Call_IdipAddVipExp,65680,TRANS_TAG_RPC_Serve_IdipAddVipExp,65682,TRANS_TAG_RPC_Call_AddWorldChannelTplMessage,65683,TRANS_TAG_RPC_Serve_AddWorldChannelTplMessage,65685,TRANS_TAG_RPC_Call_GetClubHouseMeditation,65686,TRANS_TAG_RPC_Serve_GetClubHouseMeditation,65688,TRANS_TAG_RPC_Call_AddFame,65689,TRANS_TAG_RPC_Serve_AddFame,65690,TRANS_TAG_RPC_Call_UpdateCliqueKongfuAttrib,65691,TRANS_TAG_RPC_Serve_UpdateCliqueKongfuAttrib,65692,TRANS_TAG_RPC_Call_AddAwardExp,65693,TRANS_TAG_RPC_Serve_AddAwardExp,65695,TRANS_TAG_RPC_Call_EscortBoatHijackBattleWin,65696,TRANS_TAG_RPC_Serve_EscortBoatHijackBattleWin,65697,TRANS_TAG_RPC_Call_EscortBoatRecoverBattleWin,65698,TRANS_TAG_RPC_Serve_EscortBoatRecoverBattleWin,65699,TRANS_TAG_RPC_Call_EscortBoatRecoverBattleLose,65700,TRANS_TAG_RPC_Serve_EscortBoatRecoverBattleLose,65701,TRANS_TAG_RPC_Call_UpdateClubHousePlayer,65702,TRANS_TAG_RPC_Serve_UpdateClubHousePlayer,65703,TRANS_TAG_RPC_Call_PaymentNotify,65704,TRANS_TAG_RPC_Serve_PaymentNotify,65705,TRANS_TAG_RPC_Call_XdgmGetUserInfo,65706,TRANS_TAG_RPC_Serve_XdgmGetUserInfo,65707,TRANS_TAG_RPC_Call_XdgmGetUserRank,65708,TRANS_TAG_RPC_Serve_XdgmGetUserRank,65709,TRANS_TAG_RPC_Call_XdgmCliqueList,65710,TRANS_TAG_RPC_Serve_XdgmCliqueList,65711,TRANS_TAG_RPC_Call_XdgmLockPlayer,65712,TRANS_TAG_RPC_Serve_XdgmLockPlayer,65713,TRANS_TAG_RPC_Call_XdgmGagPlayer,65714,TRANS_TAG_RPC_Serve_XdgmGagPlayer,65715,TRANS_TAG_RPC_Call_XdgmGetNormalEventInfo,65716,TRANS_TAG_RPC_Serve_XdgmGetNormalEventInfo,65717,TRANS_TAG_RPC_Call_XdgmGetJsonEventInfo,65718,TRANS_TAG_RPC_Serve_XdgmGetJsonEventInfo,65719,TRANS_TAG_RPC_Call_XdgmGetEventAwardInfo,65720,TRANS_TAG_RPC_Serve_XdgmGetEventAwardInfo,65721,TRANS_TAG_RPC_Call_XdgmSendMail,65722,TRANS_TAG_RPC_Serve_XdgmSendMail,65723,TRANS_TAG_RPC_Call_XdgmSendGameLamp,65724,TRANS_TAG_RPC_Serve_XdgmSendGameLamp,65725,TRANS_TAG_RPC_Call_XdgmSendMailAll,65726,TRANS_TAG_RPC_Serve_XdgmSendMailAll,65727,TRANS_TAG_RPC_Call_XdgmUpdateNormalEventInfo,65728,TRANS_TAG_RPC_Serve_XdgmUpdateNormalEventInfo,65729,TRANS_TAG_RPC_Call_XdgmUpdateEventAwards,65730,TRANS_TAG_RPC_Serve_XdgmUpdateEventAwards,65731,TRANS_TAG_RPC_Call_XdgmGetTextEvents,65732,TRANS_TAG_RPC_Serve_XdgmGetTextEvents,65733,TRANS_TAG_RPC_Call_XdgmSearchGameLamp,65734,TRANS_TAG_RPC_Serve_XdgmSearchGameLamp,65735,TRANS_TAG_RPC_Call_XdgmDelGameLamp,65736,TRANS_TAG_RPC_Serve_XdgmDelGameLamp,65737,TRANS_TAG_RPC_Call_XdgmAddVipExp,65738,TRANS_TAG_RPC_Serve_XdgmAddVipExp,65739,TRANS_TAG_RPC_Call_XdgmSetPaymentsPresent,65740,TRANS_TAG_RPC_Serve_XdgmSetPaymentsPresent,65741,TRANS_TAG_RPC_Call_GetPresentRule,65742,TRANS_TAG_RPC_Serve_GetPresentRule,65743,TRANS_TAG_RPC_Call_XdgmReloadGiftCode,65744,TRANS_TAG_RPC_Serve_XdgmReloadGiftCode,65745,TRANS_TAG_RPC_Call_ArenaInitPlayerArenaRank,65746,TRANS_TAG_RPC_Serve_ArenaInitPlayerArenaRank,65747,TRANS_TAG_RPC_Call_PlayerUpdateRankDatas,65748,TRANS_TAG_RPC_Serve_PlayerUpdateRankDatas,65749,TRANS_TAG_RPC_Call_PlayerUpdateRankDatasForTwoKey,65750,TRANS_TAG_RPC_Serve_PlayerUpdateRankDatasForTwoKey,65751,TRANS_TAG_RPC_Call_CronGetOnlineCount,65752,TRANS_TAG_RPC_Serve_CronGetOnlineCount,65754,TRANS_TAG_RPC_Call_DespairUpdatePlayerDatas,65755,TRANS_TAG_RPC_Serve_DespairUpdatePlayerDatas,65756,TRANS_TAG_RPC_Call_DespairGetBattleRecord,65757,TRANS_TAG_RPC_Serve_DespairGetBattleRecord,65758,TRANS_TAG_RPC_Call_DespairGetBossInfo,65759,TRANS_TAG_RPC_Serve_DespairGetBossInfo,65760,TRANS_TAG_RPC_Call_DespairSetBossInfo,65761,TRANS_TAG_RPC_Serve_DespairSetBossInfo,65762,TRANS_TAG_RPC_Call_DespairGetBossHistory,65763,TRANS_TAG_RPC_Serve_DespairGetBossHistory,65764,TRANS_TAG_RPC_Call_DespairSendAwards,65765,TRANS_TAG_RPC_Serve_DespairSendAwards,65767,TRANS_TAG_RPC_Call_DespairNotifyPass,65768,TRANS_TAG_RPC_Serve_DespairNotifyPass,65769,TRANS_TAG_RPC_Call_DespairGetBossBattleNum,65770,TRANS_TAG_RPC_Serve_DespairGetBossBattleNum,65771,TRANS_TAG_RPC_Call_DespairSyncBattleRecord,65772,TRANS_TAG_RPC_Serve_DespairSyncBattleRecord,65773,TRANS_TAG_RPC_Call_BuddyUpgradeLevel,65774,TRANS_TAG_RPC_Serve_BuddyUpgradeLevel,65775,TRANS_TAG_RPC_Call_DespairSendTopAwards,65776,TRANS_TAG_RPC_Serve_DespairSendTopAwards,65777,TRANS_TAG_RPC_Call_ExchangeGiftCode,65778,TRANS_TAG_RPC_Serve_ExchangeGiftCode,65779,TRANS_TAG_RPC_Call_ArenaSendPassiveMail,65780,TRANS_TAG_RPC_Serve_ArenaSendPassiveMail,65781,TRANS_TAG_RPC_Call_MultiLevelBroadcast,65782,TRANS_TAG_RPC_Serve_MultiLevelBroadcast,65783,TRANS_TAG_RPC_Call_MultiLevelRoomMatch,65784,TRANS_TAG_RPC_Serve_MultiLevelRoomMatch,65785,TRANS_TAG_RPC_Call_MultiLevelPlayerMatch,65786,TRANS_TAG_RPC_Serve_MultiLevelPlayerMatch,65787,TRANS_TAG_RPC_Call_MultiLevelOnMatch,65788,TRANS_TAG_RPC_Serve_MultiLevelOnMatch,65789,TRANS_TAG_RPC_Call_MultiLevelNotifyMatchPlayerInfo,65790,TRANS_TAG_RPC_Serve_MultiLevelNotifyMatchPlayerInfo,65791,TRANS_TAG_RPC_Call_MultiLevelMatchingInfo,65792,TRANS_TAG_RPC_Serve_MultiLevelMatchingInfo,65793,TRANS_TAG_RPC_Call_TaoYuanBless,65794,TRANS_TAG_RPC_Serve_TaoYuanBless,65795,TRANS_TAG_RPC_Call_TaoYuanFriendInfo,65796,TRANS_TAG_RPC_Serve_TaoYuanFriendInfo"))

	return file.EndTrans()
}

	const (
		TRANS_TAG_DISPOSE_EVENT = iota + uint32(1)<<16
		TRANS_TAG_CMD
		TRANS_TAG_PREPARE_STORE_EVENT
		TRANS_TAG_SESSION_STATE_TIMER
		TRANS_TAG_BattleRoom
		TRANS_TAG_RPC_Call_AddRecord
		TRANS_TAG_RPC_Serve_AddRecord
		TRANS_TAG_RPC_Call_GetFriendsWithMultiLevel
		TRANS_TAG_RPC_Serve_GetFriendsWithMultiLevel
		TRANS_TAG_RPC_Call_CreateAnnouncement
		TRANS_TAG_RPC_Serve_CreateAnnouncement
		TRANS_TAG_RPC_Call_EnterArena
		TRANS_TAG_RPC_Serve_EnterArena
		TRANS_TAG_RPC_Call_SwapPlayerRank
		TRANS_TAG_RPC_Serve_SwapPlayerRank
		TRANS_TAG_RPC_Call_MailSend
		TRANS_TAG_RPC_Serve_MailSend
		TRANS_TAG_RPC_Call_InviteFriendWithMultiLevel
		TRANS_TAG_RPC_Serve_InviteFriendWithMultiLevel
		TRANS_TAG_RPC_Call_AwardMultiLevel
		TRANS_TAG_RPC_Serve_AwardMultiLevel
		TRANS_TAG_RPC_Call_GetPlayerMultiLevelInfo
		TRANS_TAG_RPC_Serve_GetPlayerMultiLevelInfo
		TRANS_TAG_RPC_Call_SetPlayerInfo
		TRANS_TAG_RPC_Serve_SetPlayerInfo
		TRANS_TAG_RPC_Call_GetPlayerInfo
		TRANS_TAG_RPC_Serve_GetPlayerInfo
		TRANS_TAG_RPC_Call_GetPlayerInfoWithOpenId
		TRANS_TAG_RPC_Serve_GetPlayerInfoWithOpenId
		TRANS_TAG_RPC_Call_GetTargetPlayerRank
		TRANS_TAG_RPC_Serve_GetTargetPlayerRank
		TRANS_TAG_RPC_Call_NewPlayerFighter
		TRANS_TAG_RPC_Serve_NewPlayerFighter
		TRANS_TAG_RPC_Call_AwardArenaBox
		TRANS_TAG_RPC_Serve_AwardArenaBox
		TRANS_TAG_RPC_Call_GetTargetFighterForDrivingSwordVisting
		TRANS_TAG_RPC_Serve_GetTargetFighterForDrivingSwordVisting
		TRANS_TAG_TlogHeart
		TRANS_TAG_RPC_Call_IdipBanUser
		TRANS_TAG_RPC_Serve_IdipBanUser
		TRANS_TAG_RPC_Call_IdipUnBanUser
		TRANS_TAG_RPC_Serve_IdipUnBanUser
		TRANS_TAG_RPC_Call_IdipGetUserInfo
		TRANS_TAG_RPC_Serve_IdipGetUserInfo
		TRANS_TAG_RPC_Call_IdipGetEquipInfo
		TRANS_TAG_RPC_Serve_IdipGetEquipInfo
		TRANS_TAG_RPC_Call_IdipGetBagInfo
		TRANS_TAG_RPC_Serve_IdipGetBagInfo
		TRANS_TAG_RPC_Call_IdipGetSoulInfo
		TRANS_TAG_RPC_Serve_IdipGetSoulInfo
		TRANS_TAG_RPC_Call_IdipSendItem
		TRANS_TAG_RPC_Serve_IdipSendItem
		TRANS_TAG_RPC_Call_IdipDelItem
		TRANS_TAG_RPC_Serve_IdipDelItem
		TRANS_TAG_RPC_Call_IdipUpdateMoney
		TRANS_TAG_RPC_Serve_IdipUpdateMoney
		TRANS_TAG_RPC_Call_IdipUpdateExp
		TRANS_TAG_RPC_Serve_IdipUpdateExp
		TRANS_TAG_RPC_Call_IdipUpdatePhysical
		TRANS_TAG_RPC_Serve_IdipUpdatePhysical
		TRANS_TAG_RPC_Call_IdipUpdateHeart
		TRANS_TAG_RPC_Serve_IdipUpdateHeart
		TRANS_TAG_RPC_Call_SendHeartToPlatformFriend
		TRANS_TAG_RPC_Serve_SendHeartToPlatformFriend
		TRANS_TAG_RPC_Call_SendHeartToGameFriend
		TRANS_TAG_RPC_Serve_SendHeartToGameFriend
		TRANS_TAG_RPC_Call_SendHeartToAllGameFriends
		TRANS_TAG_RPC_Serve_SendHeartToAllGameFriends
		TRANS_TAG_RPC_Call_GetOnlineNumber
		TRANS_TAG_RPC_Serve_GetOnlineNumber
		TRANS_TAG_GlobalMail
		TRANS_TAG_GlobalMailLoading
		TRANS_TAG_RPC_Call_MailBatchSend
		TRANS_TAG_RPC_Serve_MailBatchSend
		TRANS_TAG_RPC_Call_IdipGetSwordInfo
		TRANS_TAG_RPC_Serve_IdipGetSwordInfo
		TRANS_TAG_RPC_Call_IdipGetPetInfo
		TRANS_TAG_RPC_Serve_IdipGetPetInfo
		TRANS_TAG_RPC_Call_IdipUpdateGameLamp
		TRANS_TAG_RPC_Serve_IdipUpdateGameLamp
		TRANS_TAG_RPC_Call_IdipSendMail
		TRANS_TAG_RPC_Serve_IdipSendMail
		TRANS_TAG_GlobalPostMan
		TRANS_TAG_RPC_Call_DeleteItem
		TRANS_TAG_RPC_Serve_DeleteItem
		TRANS_TAG_RPC_Call_RefuseMultiLevelRoomInvite
		TRANS_TAG_RPC_Serve_RefuseMultiLevelRoomInvite
		TRANS_TAG_RPC_Call_StartMultiLevel
		TRANS_TAG_RPC_Serve_StartMultiLevel
		TRANS_TAG_RPC_Call_MultiLevelChangeBuddy
		TRANS_TAG_RPC_Serve_MultiLevelChangeBuddy
		TRANS_TAG_RPC_Call_MultiLevelChangeForm
		TRANS_TAG_RPC_Serve_MultiLevelChangeForm
		TRANS_TAG_DoLogin
		TRANS_TAG_RPC_Call_IdipAqBanUser
		TRANS_TAG_RPC_Serve_IdipAqBanUser
		TRANS_TAG_RPC_Call_IdipAqRelievePunish
		TRANS_TAG_RPC_Serve_IdipAqRelievePunish
		TRANS_TAG_RPC_Call_IdipAqSendMail
		TRANS_TAG_RPC_Serve_IdipAqSendMail
		TRANS_TAG_RPC_Call_IdipGetRankInfoGs
		TRANS_TAG_RPC_Serve_IdipGetRankInfoGs
		TRANS_TAG_RPC_Call_IdipGetRankInfoHd
		TRANS_TAG_RPC_Serve_IdipGetRankInfoHd
		TRANS_TAG_RPC_Call_IdipCleanData
		TRANS_TAG_RPC_Serve_IdipCleanData
		TRANS_TAG_RPC_Call_IdipSetSoulLevel
		TRANS_TAG_RPC_Serve_IdipSetSoulLevel
		TRANS_TAG_RPC_Call_IdipSetSwordLevel
		TRANS_TAG_RPC_Serve_IdipSetSwordLevel
		TRANS_TAG_RPC_Call_IdipAddPet
		TRANS_TAG_RPC_Serve_IdipAddPet
		TRANS_TAG_RPC_Call_GetArenaRank
		TRANS_TAG_RPC_Serve_GetArenaRank
		TRANS_TAG_RPC_Call_IdipSendAllMail
		TRANS_TAG_RPC_Serve_IdipSendAllMail
		TRANS_TAG_RPC_Call_IdipGameLampInfo
		TRANS_TAG_RPC_Serve_IdipGameLampInfo
		TRANS_TAG_RPC_Call_IdipDelNotice
		TRANS_TAG_RPC_Serve_IdipDelNotice
		TRANS_TAG_RPC_Call_TssUserLogin
		TRANS_TAG_RPC_Serve_TssUserLogin
		TRANS_TAG_RPC_Call_TssUserLogout
		TRANS_TAG_RPC_Serve_TssUserLogout
		TRANS_TAG_RPC_Call_TssRecvData
		TRANS_TAG_RPC_Serve_TssRecvData
		TRANS_TAG_RPC_Call_TssSendData
		TRANS_TAG_RPC_Serve_TssSendData
		TRANS_TAG_RPC_Call_GetGlobalVipCount
		TRANS_TAG_RPC_Serve_GetGlobalVipCount
		TRANS_TAG_RPC_Call_GetGlobalLevelVipCount
		TRANS_TAG_RPC_Serve_GetGlobalLevelVipCount
		TRANS_TAG_RPC_Call_OperateGroupBuyCount
		TRANS_TAG_RPC_Serve_OperateGroupBuyCount
		TRANS_TAG_GlobalWorldChannel
		TRANS_TAG_RPC_Call_DecMoney
		TRANS_TAG_RPC_Serve_DecMoney
		TRANS_TAG_RPC_Call_IncMoney
		TRANS_TAG_RPC_Serve_IncMoney
		TRANS_TAG_RPC_Call_IdipGetUserFight
		TRANS_TAG_RPC_Serve_IdipGetUserFight
		TRANS_TAG_RPC_Call_IdipGetHardLevelStatus
		TRANS_TAG_RPC_Serve_IdipGetHardLevelStatus
		TRANS_TAG_RPC_Call_IdipAddVipExp
		TRANS_TAG_RPC_Serve_IdipAddVipExp
		TRANS_TAG_HttpAsync
		TRANS_TAG_RPC_Call_AddWorldChannelTplMessage
		TRANS_TAG_RPC_Serve_AddWorldChannelTplMessage
		TRANS_TAG_WebDebugger
		TRANS_TAG_RPC_Call_GetClubHouseMeditation
		TRANS_TAG_RPC_Serve_GetClubHouseMeditation
		TRANS_TAG_GlobalCliquesalary
		TRANS_TAG_RPC_Call_AddFame
		TRANS_TAG_RPC_Serve_AddFame
		TRANS_TAG_RPC_Call_UpdateCliqueKongfuAttrib
		TRANS_TAG_RPC_Serve_UpdateCliqueKongfuAttrib
		TRANS_TAG_RPC_Call_AddAwardExp
		TRANS_TAG_RPC_Serve_AddAwardExp
		TRANS_TAG_ESCORT_BOAT_TIMER
		TRANS_TAG_RPC_Call_EscortBoatHijackBattleWin
		TRANS_TAG_RPC_Serve_EscortBoatHijackBattleWin
		TRANS_TAG_RPC_Call_EscortBoatRecoverBattleWin
		TRANS_TAG_RPC_Serve_EscortBoatRecoverBattleWin
		TRANS_TAG_RPC_Call_EscortBoatRecoverBattleLose
		TRANS_TAG_RPC_Serve_EscortBoatRecoverBattleLose
		TRANS_TAG_RPC_Call_UpdateClubHousePlayer
		TRANS_TAG_RPC_Serve_UpdateClubHousePlayer
		TRANS_TAG_RPC_Call_PaymentNotify
		TRANS_TAG_RPC_Serve_PaymentNotify
		TRANS_TAG_RPC_Call_XdgmGetUserInfo
		TRANS_TAG_RPC_Serve_XdgmGetUserInfo
		TRANS_TAG_RPC_Call_XdgmGetUserRank
		TRANS_TAG_RPC_Serve_XdgmGetUserRank
		TRANS_TAG_RPC_Call_XdgmCliqueList
		TRANS_TAG_RPC_Serve_XdgmCliqueList
		TRANS_TAG_RPC_Call_XdgmLockPlayer
		TRANS_TAG_RPC_Serve_XdgmLockPlayer
		TRANS_TAG_RPC_Call_XdgmGagPlayer
		TRANS_TAG_RPC_Serve_XdgmGagPlayer
		TRANS_TAG_RPC_Call_XdgmGetNormalEventInfo
		TRANS_TAG_RPC_Serve_XdgmGetNormalEventInfo
		TRANS_TAG_RPC_Call_XdgmGetJsonEventInfo
		TRANS_TAG_RPC_Serve_XdgmGetJsonEventInfo
		TRANS_TAG_RPC_Call_XdgmGetEventAwardInfo
		TRANS_TAG_RPC_Serve_XdgmGetEventAwardInfo
		TRANS_TAG_RPC_Call_XdgmSendMail
		TRANS_TAG_RPC_Serve_XdgmSendMail
		TRANS_TAG_RPC_Call_XdgmSendGameLamp
		TRANS_TAG_RPC_Serve_XdgmSendGameLamp
		TRANS_TAG_RPC_Call_XdgmSendMailAll
		TRANS_TAG_RPC_Serve_XdgmSendMailAll
		TRANS_TAG_RPC_Call_XdgmUpdateNormalEventInfo
		TRANS_TAG_RPC_Serve_XdgmUpdateNormalEventInfo
		TRANS_TAG_RPC_Call_XdgmUpdateEventAwards
		TRANS_TAG_RPC_Serve_XdgmUpdateEventAwards
		TRANS_TAG_RPC_Call_XdgmGetTextEvents
		TRANS_TAG_RPC_Serve_XdgmGetTextEvents
		TRANS_TAG_RPC_Call_XdgmSearchGameLamp
		TRANS_TAG_RPC_Serve_XdgmSearchGameLamp
		TRANS_TAG_RPC_Call_XdgmDelGameLamp
		TRANS_TAG_RPC_Serve_XdgmDelGameLamp
		TRANS_TAG_RPC_Call_XdgmAddVipExp
		TRANS_TAG_RPC_Serve_XdgmAddVipExp
		TRANS_TAG_RPC_Call_XdgmSetPaymentsPresent
		TRANS_TAG_RPC_Serve_XdgmSetPaymentsPresent
		TRANS_TAG_RPC_Call_GetPresentRule
		TRANS_TAG_RPC_Serve_GetPresentRule
		TRANS_TAG_RPC_Call_XdgmReloadGiftCode
		TRANS_TAG_RPC_Serve_XdgmReloadGiftCode
		TRANS_TAG_RPC_Call_ArenaInitPlayerArenaRank
		TRANS_TAG_RPC_Serve_ArenaInitPlayerArenaRank
		TRANS_TAG_RPC_Call_PlayerUpdateRankDatas
		TRANS_TAG_RPC_Serve_PlayerUpdateRankDatas
		TRANS_TAG_RPC_Call_PlayerUpdateRankDatasForTwoKey
		TRANS_TAG_RPC_Serve_PlayerUpdateRankDatasForTwoKey
		TRANS_TAG_RPC_Call_CronGetOnlineCount
		TRANS_TAG_RPC_Serve_CronGetOnlineCount
		TRANS_TAG_DespairCheckStart
		TRANS_TAG_RPC_Call_DespairUpdatePlayerDatas
		TRANS_TAG_RPC_Serve_DespairUpdatePlayerDatas
		TRANS_TAG_RPC_Call_DespairGetBattleRecord
		TRANS_TAG_RPC_Serve_DespairGetBattleRecord
		TRANS_TAG_RPC_Call_DespairGetBossInfo
		TRANS_TAG_RPC_Serve_DespairGetBossInfo
		TRANS_TAG_RPC_Call_DespairSetBossInfo
		TRANS_TAG_RPC_Serve_DespairSetBossInfo
		TRANS_TAG_RPC_Call_DespairGetBossHistory
		TRANS_TAG_RPC_Serve_DespairGetBossHistory
		TRANS_TAG_RPC_Call_DespairSendAwards
		TRANS_TAG_RPC_Serve_DespairSendAwards
		TRANS_TAG_DespairStartBoss
		TRANS_TAG_RPC_Call_DespairNotifyPass
		TRANS_TAG_RPC_Serve_DespairNotifyPass
		TRANS_TAG_RPC_Call_DespairGetBossBattleNum
		TRANS_TAG_RPC_Serve_DespairGetBossBattleNum
		TRANS_TAG_RPC_Call_DespairSyncBattleRecord
		TRANS_TAG_RPC_Serve_DespairSyncBattleRecord
		TRANS_TAG_RPC_Call_BuddyUpgradeLevel
		TRANS_TAG_RPC_Serve_BuddyUpgradeLevel
		TRANS_TAG_RPC_Call_DespairSendTopAwards
		TRANS_TAG_RPC_Serve_DespairSendTopAwards
		TRANS_TAG_RPC_Call_ExchangeGiftCode
		TRANS_TAG_RPC_Serve_ExchangeGiftCode
		TRANS_TAG_RPC_Call_ArenaSendPassiveMail
		TRANS_TAG_RPC_Serve_ArenaSendPassiveMail
		TRANS_TAG_RPC_Call_MultiLevelBroadcast
		TRANS_TAG_RPC_Serve_MultiLevelBroadcast
		TRANS_TAG_RPC_Call_MultiLevelRoomMatch
		TRANS_TAG_RPC_Serve_MultiLevelRoomMatch
		TRANS_TAG_RPC_Call_MultiLevelPlayerMatch
		TRANS_TAG_RPC_Serve_MultiLevelPlayerMatch
		TRANS_TAG_RPC_Call_MultiLevelOnMatch
		TRANS_TAG_RPC_Serve_MultiLevelOnMatch
		TRANS_TAG_RPC_Call_MultiLevelNotifyMatchPlayerInfo
		TRANS_TAG_RPC_Serve_MultiLevelNotifyMatchPlayerInfo
		TRANS_TAG_RPC_Call_MultiLevelMatchingInfo
		TRANS_TAG_RPC_Serve_MultiLevelMatchingInfo
		TRANS_TAG_RPC_Call_TaoYuanBless
		TRANS_TAG_RPC_Serve_TaoYuanBless
		TRANS_TAG_RPC_Call_TaoYuanFriendInfo
		TRANS_TAG_RPC_Serve_TaoYuanFriendInfo
	)
	const (
		RPC_Remote_AddRecord = "RemoteServe.AddRecord"
		RPC_Remote_GetFriendsWithMultiLevel = "RemoteServe.GetFriendsWithMultiLevel"
		RPC_Remote_CreateAnnouncement = "RemoteServe.CreateAnnouncement"
		RPC_Remote_EnterArena = "RemoteServe.EnterArena"
		RPC_Remote_SwapPlayerRank = "RemoteServe.SwapPlayerRank"
		RPC_Remote_MailSend = "RemoteServe.MailSend"
		RPC_Remote_InviteFriendWithMultiLevel = "RemoteServe.InviteFriendWithMultiLevel"
		RPC_Remote_AwardMultiLevel = "RemoteServe.AwardMultiLevel"
		RPC_Remote_GetPlayerMultiLevelInfo = "RemoteServe.GetPlayerMultiLevelInfo"
		RPC_Remote_SetPlayerInfo = "RemoteServe.SetPlayerInfo"
		RPC_Remote_GetPlayerInfo = "RemoteServe.GetPlayerInfo"
		RPC_Remote_GetPlayerInfoWithOpenId = "RemoteServe.GetPlayerInfoWithOpenId"
		RPC_Remote_GetTargetPlayerRank = "RemoteServe.GetTargetPlayerRank"
		RPC_Remote_NewPlayerFighter = "RemoteServe.NewPlayerFighter"
		RPC_Remote_AwardArenaBox = "RemoteServe.AwardArenaBox"
		RPC_Remote_GetTargetFighterForDrivingSwordVisting = "RemoteServe.GetTargetFighterForDrivingSwordVisting"
		RPC_Remote_IdipBanUser = "RemoteServe.IdipBanUser"
		RPC_Remote_IdipUnBanUser = "RemoteServe.IdipUnBanUser"
		RPC_Remote_IdipGetUserInfo = "RemoteServe.IdipGetUserInfo"
		RPC_Remote_IdipGetEquipInfo = "RemoteServe.IdipGetEquipInfo"
		RPC_Remote_IdipGetBagInfo = "RemoteServe.IdipGetBagInfo"
		RPC_Remote_IdipGetSoulInfo = "RemoteServe.IdipGetSoulInfo"
		RPC_Remote_IdipSendItem = "RemoteServe.IdipSendItem"
		RPC_Remote_IdipDelItem = "RemoteServe.IdipDelItem"
		RPC_Remote_IdipUpdateMoney = "RemoteServe.IdipUpdateMoney"
		RPC_Remote_IdipUpdateExp = "RemoteServe.IdipUpdateExp"
		RPC_Remote_IdipUpdatePhysical = "RemoteServe.IdipUpdatePhysical"
		RPC_Remote_IdipUpdateHeart = "RemoteServe.IdipUpdateHeart"
		RPC_Remote_SendHeartToPlatformFriend = "RemoteServe.SendHeartToPlatformFriend"
		RPC_Remote_SendHeartToGameFriend = "RemoteServe.SendHeartToGameFriend"
		RPC_Remote_SendHeartToAllGameFriends = "RemoteServe.SendHeartToAllGameFriends"
		RPC_Remote_GetOnlineNumber = "RemoteServe.GetOnlineNumber"
		RPC_Remote_MailBatchSend = "RemoteServe.MailBatchSend"
		RPC_Remote_IdipGetSwordInfo = "RemoteServe.IdipGetSwordInfo"
		RPC_Remote_IdipGetPetInfo = "RemoteServe.IdipGetPetInfo"
		RPC_Remote_IdipUpdateGameLamp = "RemoteServe.IdipUpdateGameLamp"
		RPC_Remote_IdipSendMail = "RemoteServe.IdipSendMail"
		RPC_Remote_DeleteItem = "RemoteServe.DeleteItem"
		RPC_Remote_RefuseMultiLevelRoomInvite = "RemoteServe.RefuseMultiLevelRoomInvite"
		RPC_Remote_StartMultiLevel = "RemoteServe.StartMultiLevel"
		RPC_Remote_MultiLevelChangeBuddy = "RemoteServe.MultiLevelChangeBuddy"
		RPC_Remote_MultiLevelChangeForm = "RemoteServe.MultiLevelChangeForm"
		RPC_Remote_IdipAqBanUser = "RemoteServe.IdipAqBanUser"
		RPC_Remote_IdipAqRelievePunish = "RemoteServe.IdipAqRelievePunish"
		RPC_Remote_IdipAqSendMail = "RemoteServe.IdipAqSendMail"
		RPC_Remote_IdipGetRankInfoGs = "RemoteServe.IdipGetRankInfoGs"
		RPC_Remote_IdipGetRankInfoHd = "RemoteServe.IdipGetRankInfoHd"
		RPC_Remote_IdipCleanData = "RemoteServe.IdipCleanData"
		RPC_Remote_IdipSetSoulLevel = "RemoteServe.IdipSetSoulLevel"
		RPC_Remote_IdipSetSwordLevel = "RemoteServe.IdipSetSwordLevel"
		RPC_Remote_IdipAddPet = "RemoteServe.IdipAddPet"
		RPC_Remote_GetArenaRank = "RemoteServe.GetArenaRank"
		RPC_Remote_IdipSendAllMail = "RemoteServe.IdipSendAllMail"
		RPC_Remote_IdipGameLampInfo = "RemoteServe.IdipGameLampInfo"
		RPC_Remote_IdipDelNotice = "RemoteServe.IdipDelNotice"
		RPC_Remote_TssUserLogin = "RemoteServe.TssUserLogin"
		RPC_Remote_TssUserLogout = "RemoteServe.TssUserLogout"
		RPC_Remote_TssRecvData = "RemoteServe.TssRecvData"
		RPC_Remote_TssSendData = "RemoteServe.TssSendData"
		RPC_Remote_GetGlobalVipCount = "RemoteServe.GetGlobalVipCount"
		RPC_Remote_GetGlobalLevelVipCount = "RemoteServe.GetGlobalLevelVipCount"
		RPC_Remote_OperateGroupBuyCount = "RemoteServe.OperateGroupBuyCount"
		RPC_Remote_DecMoney = "RemoteServe.DecMoney"
		RPC_Remote_IncMoney = "RemoteServe.IncMoney"
		RPC_Remote_IdipGetUserFight = "RemoteServe.IdipGetUserFight"
		RPC_Remote_IdipGetHardLevelStatus = "RemoteServe.IdipGetHardLevelStatus"
		RPC_Remote_IdipAddVipExp = "RemoteServe.IdipAddVipExp"
		RPC_Remote_AddWorldChannelTplMessage = "RemoteServe.AddWorldChannelTplMessage"
		RPC_Remote_GetClubHouseMeditation = "RemoteServe.GetClubHouseMeditation"
		RPC_Remote_AddFame = "RemoteServe.AddFame"
		RPC_Remote_UpdateCliqueKongfuAttrib = "RemoteServe.UpdateCliqueKongfuAttrib"
		RPC_Remote_AddAwardExp = "RemoteServe.AddAwardExp"
		RPC_Remote_EscortBoatHijackBattleWin = "RemoteServe.EscortBoatHijackBattleWin"
		RPC_Remote_EscortBoatRecoverBattleWin = "RemoteServe.EscortBoatRecoverBattleWin"
		RPC_Remote_EscortBoatRecoverBattleLose = "RemoteServe.EscortBoatRecoverBattleLose"
		RPC_Remote_UpdateClubHousePlayer = "RemoteServe.UpdateClubHousePlayer"
		RPC_Remote_PaymentNotify = "RemoteServe.PaymentNotify"
		RPC_Remote_XdgmGetUserInfo = "RemoteServe.XdgmGetUserInfo"
		RPC_Remote_XdgmGetUserRank = "RemoteServe.XdgmGetUserRank"
		RPC_Remote_XdgmCliqueList = "RemoteServe.XdgmCliqueList"
		RPC_Remote_XdgmLockPlayer = "RemoteServe.XdgmLockPlayer"
		RPC_Remote_XdgmGagPlayer = "RemoteServe.XdgmGagPlayer"
		RPC_Remote_XdgmGetNormalEventInfo = "RemoteServe.XdgmGetNormalEventInfo"
		RPC_Remote_XdgmGetJsonEventInfo = "RemoteServe.XdgmGetJsonEventInfo"
		RPC_Remote_XdgmGetEventAwardInfo = "RemoteServe.XdgmGetEventAwardInfo"
		RPC_Remote_XdgmSendMail = "RemoteServe.XdgmSendMail"
		RPC_Remote_XdgmSendGameLamp = "RemoteServe.XdgmSendGameLamp"
		RPC_Remote_XdgmSendMailAll = "RemoteServe.XdgmSendMailAll"
		RPC_Remote_XdgmUpdateNormalEventInfo = "RemoteServe.XdgmUpdateNormalEventInfo"
		RPC_Remote_XdgmUpdateEventAwards = "RemoteServe.XdgmUpdateEventAwards"
		RPC_Remote_XdgmGetTextEvents = "RemoteServe.XdgmGetTextEvents"
		RPC_Remote_XdgmSearchGameLamp = "RemoteServe.XdgmSearchGameLamp"
		RPC_Remote_XdgmDelGameLamp = "RemoteServe.XdgmDelGameLamp"
		RPC_Remote_XdgmAddVipExp = "RemoteServe.XdgmAddVipExp"
		RPC_Remote_XdgmSetPaymentsPresent = "RemoteServe.XdgmSetPaymentsPresent"
		RPC_Remote_GetPresentRule = "RemoteServe.GetPresentRule"
		RPC_Remote_XdgmReloadGiftCode = "RemoteServe.XdgmReloadGiftCode"
		RPC_Remote_ArenaInitPlayerArenaRank = "RemoteServe.ArenaInitPlayerArenaRank"
		RPC_Remote_PlayerUpdateRankDatas = "RemoteServe.PlayerUpdateRankDatas"
		RPC_Remote_PlayerUpdateRankDatasForTwoKey = "RemoteServe.PlayerUpdateRankDatasForTwoKey"
		RPC_Remote_CronGetOnlineCount = "RemoteServe.CronGetOnlineCount"
		RPC_Remote_DespairUpdatePlayerDatas = "RemoteServe.DespairUpdatePlayerDatas"
		RPC_Remote_DespairGetBattleRecord = "RemoteServe.DespairGetBattleRecord"
		RPC_Remote_DespairGetBossInfo = "RemoteServe.DespairGetBossInfo"
		RPC_Remote_DespairSetBossInfo = "RemoteServe.DespairSetBossInfo"
		RPC_Remote_DespairGetBossHistory = "RemoteServe.DespairGetBossHistory"
		RPC_Remote_DespairSendAwards = "RemoteServe.DespairSendAwards"
		RPC_Remote_DespairNotifyPass = "RemoteServe.DespairNotifyPass"
		RPC_Remote_DespairGetBossBattleNum = "RemoteServe.DespairGetBossBattleNum"
		RPC_Remote_DespairSyncBattleRecord = "RemoteServe.DespairSyncBattleRecord"
		RPC_Remote_BuddyUpgradeLevel = "RemoteServe.BuddyUpgradeLevel"
		RPC_Remote_DespairSendTopAwards = "RemoteServe.DespairSendTopAwards"
		RPC_Remote_ExchangeGiftCode = "RemoteServe.ExchangeGiftCode"
		RPC_Remote_ArenaSendPassiveMail = "RemoteServe.ArenaSendPassiveMail"
		RPC_Remote_MultiLevelBroadcast = "RemoteServe.MultiLevelBroadcast"
		RPC_Remote_MultiLevelRoomMatch = "RemoteServe.MultiLevelRoomMatch"
		RPC_Remote_MultiLevelPlayerMatch = "RemoteServe.MultiLevelPlayerMatch"
		RPC_Remote_MultiLevelOnMatch = "RemoteServe.MultiLevelOnMatch"
		RPC_Remote_MultiLevelNotifyMatchPlayerInfo = "RemoteServe.MultiLevelNotifyMatchPlayerInfo"
		RPC_Remote_MultiLevelMatchingInfo = "RemoteServe.MultiLevelMatchingInfo"
		RPC_Remote_TaoYuanBless = "RemoteServe.TaoYuanBless"
		RPC_Remote_TaoYuanFriendInfo = "RemoteServe.TaoYuanFriendInfo"
	)
