package player_dat


const( 
	COINS = 0
	INGOT = 1
	SWORDSOULFRAGMENT = 2
	NO_NEED_PLAY = 0
	NEED_PLAY = 1
)
const( 
	TPRESENT_DEFAULT_DISCOUNTID =  "UM140805211423554"
	TPRESENT_DEFAULT_GIFTID =  "2964073651PID201408052114235636"
)
const( 
	RESET_ARENA_TIMES_IN_HOUR = 5
	RESET_ARENA_AWARD_BOX_IN_HOUR = 21
	RESET_GHOST_LEVEL_TIMES_IN_HOUR = 5
	RESET_PET_LEVEL_TIMES_IN_HOUR = 5
	RESET_BUDDY_LEVEL_TIMES_IN_HOUR = 5
	RESET_EXP_LEVEL_TIMES_IN_HOUR = 5
	RESET_COIN_LEVEL_TIMES_IN_HOUR = 5
	RESET_RAINBOW_LEVEL_TIMES_IN_HOUR = 5
	RESET_HARD_LEVEL_TIMES_IN_HOUR = 5
	RESET_MAIN_LEVEL_TIMES_IN_HOUR = 5
	RESET_MULTI_LEVEL_TIMES_IN_HOUR = 5
	RESET_DAILY_QUEST_IN_HOUR = 5
	RESET_COIN_BOX_TIMES_IN_HOUR = 5
	RESET_INGOT_BOX_TIMES_IN_HOUR = 5
	RESET_HEART_DRAW_TIMES_IN_HOUR = 5
	RESET_BUY_PHYSICAL_TIMES_IN_HOUR = 5
	RESET_PLAYER_ACTIVITY_IN_HOUR = 5
	RESET_PVE_LEVEL_IN_HOUR = 5
	RESET_GHOST_TRAIN_INFO_IN_HOUR = 5
	RESET_BATTLE_PET_UPGRADE_INFO_IN_HOUR = 5
	RESET_BUY_HARD_LEVEL_TIMES_IN_HOUR = 5
	RESET_BUY_TOTEM_INGOT_CALL_TIMES_IN_HOUR = 5
	RESET_DRIVING_SWORD_ACTION_TIMES_IN_HOUR = 5
	RESET_BUY_RESOURCE_LEVEL_TIMES_IN_HOUR = 5
	RESET_BUY_DESPAIR_BATTLE_TIMES_IN_HOUR = 5
	RESET_CLIQUE_STORE_SEND_TIMES_IN_HOUR = 5
	RESET_CLIQUE_BUILD_DONATE_TIMES_IN_HOUR = 5
	RESET_DAILY_QUEST_STAR_AWARDED_TIMES_IN_HOUR = 5
	RESET_TAOYUAN_TIMES_IN_HOUR = 5
)
const( 
	MAX_PLAYER_ACTIVITY = 1500
)
const( 
	ARENA_LOSE_AWARD_FAME = 5
	ARENA_WIN_AWARD_FAME = 10
)
const( 
	MONTH_CARD_PER_TIMES = 30
)
const( 
	FUNC_OPEN_TYPE_BY_LOCK = 1
	FUNC_OPEN_TYPE_BY_LEVEL = 2
)
const( 
	RANK_EVERY_PAGE_NUM = 7
	RANK_OPEN_MIN_LEVEL = 15
	RANK_DESPLAY_NUM = 10000
	TYPE_BUDDY_ROLE_ID = 1
	TYPE_BUDDY_LEVEL = 2
)







 // 功能常量 
const(
	FUNC_FRIENDSHIP = 24 // 伙伴羁绊 要求等级 1
	FUNC_DIRECTLY_AWARD = 20 // 扫荡 要求等级 10
	FUNC_WORLD_CHANNEL = 23 // 世界聊天 要求等级 15
	FUNC_MEDITATION = 21 // 打坐 要求等级 16
	FUNC_ARENA = 10 // 比武场 要求等级 17
	FUNC_CLIQUE = 28 // 帮派 要求等级 18
	FUNC_TRADER = 15 // 瀛海集市 要求等级 19
	FUNC_TAOYUAN = 30 // 桃源 要求等级 20
	FUNC_RESOURCE_LEVEL = 16 // 资源关卡 要求等级 25
	FUNC_PET_VIRTUAL_ENV = 22 // 灵宠幻境 要求等级 25
	FUNC_MULTI_LEVEL = 18 // 多人关卡 要求等级 30
	FUNC_ACTIVE_LEVLE = 17 // 活动关卡 要求等级 35
	FUNC_DRIVING_SWORD = 27 // 云海御剑 要求等级 45
	FUNC_TOTEM = 26 // 阵印 要求等级 45
	FUNC_AWAKEN = 29 // 觉醒 要求等级 50
	FUNC_GHOST = 3 // 魂侍 要求权值 1000
	FUNC_HARD_LEVEL = 14 // 难度关卡 要求权值 1050
	FUNC_RAINBOW_LEVEL = 19 // 极限关卡 要求权值 1100
	FUNC_FATE_BOX = 25 // 命锁宝箱 要求权值 1200
	FUNC_BATTLE_PET = 8 // 灵宠 要求权值 1450
	FUNC_SWORD_SOUL = 7 // 剑心 要求权值 1500
)



 // 声望系统常量 
const(
	ARENA_SYSTEM = 1 // 比武场
	MULT_LEVEL_SYSTEM = 2 // 多人关卡
	CLIQUE_SYSTEM = 4 // 帮派
)



 //开元通宝 
var(
	INGOT_TO_COINS_DOUBLE_NUMS = [6]int{10, 15, 20, 30, 40, 50}
)

